### ISSUE TITLE
Testbox problems

### ISSUE THREAD

**Issue by Leftbower** [coldbox-templates/modern#1]
Using this template via box install, server start, click on link to `apprunner.cfm` and errors with `The event: app.tests is not a valid registered event.`

If I remove `app/` from the URL we get a little further as the runner loads, but then get Lucee error a quarter down the page:

`

Lucee 5.3.8.179-RC Error (expression)
--
Message | The function [info] does not exist in the String.
Stacktrace | The Error Occurred inC:\dev\apps\aaa\lib\coldbox\system\web\services\LoaderService.cfc: line 239237: */238: LoaderService function processShutdown(){239: variables.log.info( "† Shutting down ColdBox..." );240:241: // Announce shutdowncalled from&nbsp;C:\dev\apps\aaa\tests\Application.cfc: line 32
Java Stacktrace | lucee.runtime.exp.ExpressionException: The function [info] does not exist in the String.&nbsp;&nbsp;at lucee.runtime.type.util.MemberUtil.call(MemberUtil.java:158)&nbsp;&nbsp;at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:794)&nbsp;&nbsp;at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1744)&nbsp;&nbsp;at system.web.services.loaderservice_cfc$cf$2h.udfCall1(/coldbox/system/web/services/LoaderService.cfc:239)&nbsp;&nbsp;at system.web.services.loaderservice_cfc$cf$2h.udfCall(/coldbox/system/web/services/LoaderService.cfc)&nbsp;&nbsp;at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)&nbsp;&nbsp;at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)&nbsp;&nbsp;at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)&nbsp;&nbsp;at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)&nbsp;&nbsp;at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)&nbsp;&nbsp;at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911)&nbsp;&nbsp;at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)&nbsp;&nbsp;at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1744)&nbsp;&nbsp;at application_cfc$cf.udfCall(/tests/Application.cfc:32)&nbsp;&nbsp;at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)&nbsp;&nbsp;at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)&nbsp;&nbsp;at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)&nbsp;&nbsp;at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)&nbsp;&nbsp;at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)&nbsp;&nbsp;at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911)&nbsp;&nbsp;at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:437)&nbsp;&nbsp;at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:228)&nbsp;&nbsp;at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)&nbsp;&nbsp;at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2457)&nbsp;&nbsp;at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2447)&nbsp;&nbsp;at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2418)&nbsp;&nbsp;at lucee.runtime.engine.Request.exe(Request.java:44)&nbsp;&nbsp;at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179)&nbsp;&nbsp;at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125)&nbsp;&nbsp;at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)&nbsp;&nbsp;at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)&nbsp;&nbsp;at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)&nbsp;&nbsp;at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)&nbsp;&nbsp;at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)&nbsp;&nbsp;at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)&nbsp;&nbsp;at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)&nbsp;&nbsp;at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)&nbsp;&nbsp;at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)&nbsp;&nbsp;at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)&nbsp;&nbsp;at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:405)&nbsp;&nbsp;at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)&nbsp;&nbsp;at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)&nbsp;&nbsp;at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)&nbsp;&nbsp;at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)&nbsp;&nbsp;at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)&nbsp;&nbsp;at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)&nbsp;&nbsp;at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)&nbsp;&nbsp;at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)&nbsp;&nbsp;at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)&nbsp;&nbsp;at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)&nbsp;&nbsp;at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)&nbsp;&nbsp;at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)&nbsp;&nbsp;at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)&nbsp;&nbsp;at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)&nbsp;&nbsp;at runwar.Server$1.handleRequest(Server.java:511)&nbsp;&nbsp;at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)&nbsp;&nbsp;at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)&nbsp;&nbsp;at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)&nbsp;&nbsp;at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)&nbsp;&nbsp;at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)&nbsp;&nbsp;at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)&nbsp;&nbsp;at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)&nbsp;&nbsp;at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)&nbsp;&nbsp;at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)&nbsp;&nbsp;at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)&nbsp;&nbsp;at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)&nbsp;&nbsp;at java.base/java.lang.Thread.run(Thread.java:834)

`

**Comment by lmajano** [comment]
This template is still not fully operational. It's a work in progress.

**Comment by Leftbower** [comment]
Understood. I'm anxious to see what you end up with as I had tried my hand at something similar about 8 months ago and had some struggles. See this threaded discussion with Brad here:
https://boxteam.slack.com/archives/C0536GAE3/p1601337592014200

**Comment by lmajano** [comment]
we should be operational now
